// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRjZs9rA2oJmc4Ak4dK6Y5kCQt6PK9ItM',
    appId: '1:648219338530:web:fbdb6fdb82c135e5bca77b',
    messagingSenderId: '648219338530',
    projectId: 'my-project-5ee2a',
    authDomain: 'my-project-5ee2a.firebaseapp.com',
    storageBucket: 'my-project-5ee2a.appspot.com',
    measurementId: 'G-TVP5X8J0MM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN5Ej35v36vw2EUMH9P6tlhRb5fhynfqw',
    appId: '1:648219338530:android:7c4986971a604987bca77b',
    messagingSenderId: '648219338530',
    projectId: 'my-project-5ee2a',
    storageBucket: 'my-project-5ee2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpVpH5c8RjBgnugA1MAN19achBqJUs3yY',
    appId: '1:648219338530:ios:6f79f86904650a3abca77b',
    messagingSenderId: '648219338530',
    projectId: 'my-project-5ee2a',
    storageBucket: 'my-project-5ee2a.appspot.com',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpVpH5c8RjBgnugA1MAN19achBqJUs3yY',
    appId: '1:648219338530:ios:6f79f86904650a3abca77b',
    messagingSenderId: '648219338530',
    projectId: 'my-project-5ee2a',
    storageBucket: 'my-project-5ee2a.appspot.com',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRjZs9rA2oJmc4Ak4dK6Y5kCQt6PK9ItM',
    appId: '1:648219338530:web:abfbbbc3cefb1b70bca77b',
    messagingSenderId: '648219338530',
    projectId: 'my-project-5ee2a',
    authDomain: 'my-project-5ee2a.firebaseapp.com',
    storageBucket: 'my-project-5ee2a.appspot.com',
    measurementId: 'G-M9WY7EE6MM',
  );
}
